/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CardType = IDL.Variant({
  'credit' : IDL.Null,
  'debit' : IDL.Null,
});
export const LoanType = IDL.Variant({
  'home' : IDL.Null,
  'business' : IDL.Null,
  'vehicle' : IDL.Null,
});
export const Amount = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AccountLabel = IDL.Text;
export const TransferType = IDL.Variant({
  'imps' : IDL.Null,
  'neft' : IDL.Null,
  'rtgs' : IDL.Null,
});
export const Card = IDL.Record({
  'nickname' : IDL.Text,
  'cardType' : CardType,
  'last4' : IDL.Text,
  'issuer' : IDL.Text,
  'expiry' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const TransferStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const Time = IDL.Int;
export const MoneyTransfer = IDL.Record({
  'status' : TransferStatus,
  'transferType' : TransferType,
  'fromAccount' : AccountLabel,
  'beneficiary' : IDL.Text,
  'note' : IDL.Text,
  'timestamp' : Time,
  'amount' : Amount,
});
export const EmiPlan = IDL.Record({
  'emi' : IDL.Float64,
  'principal' : Amount,
  'createdAt' : Time,
  'rate' : IDL.Float64,
  'totalInterest' : IDL.Float64,
  'tenureMonths' : IDL.Nat,
  'totalPayment' : IDL.Float64,
});
export const InsuranceCategory = IDL.Variant({
  'home' : IDL.Null,
  'life' : IDL.Null,
  'vehicle' : IDL.Null,
  'health' : IDL.Null,
});
export const InsuranceInquiry = IDL.Record({
  'status' : IDL.Variant({ 'submitted' : IDL.Null, 'reviewed' : IDL.Null }),
  'notes' : IDL.Text,
  'timestamp' : Time,
  'category' : InsuranceCategory,
  'coverageAmount' : Amount,
  'contactPreference' : IDL.Text,
});
export const LoanApplication = IDL.Record({
  'status' : IDL.Variant({ 'submitted' : IDL.Null, 'underReview' : IDL.Null }),
  'documents' : IDL.Text,
  'name' : IDL.Text,
  'loanType' : LoanType,
  'income' : Amount,
  'timestamp' : Time,
  'tenure' : IDL.Nat,
  'amount' : Amount,
  'purpose' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCard' : IDL.Func(
      [IDL.Text, CardType, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'applyLoan' : IDL.Func(
      [LoanType, IDL.Text, Amount, IDL.Nat, Amount, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTransfer' : IDL.Func(
      [AccountLabel, IDL.Text, Amount, IDL.Text, TransferType],
      [],
      [],
    ),
  'getAllCards' : IDL.Func([], [IDL.Vec(Card)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'loanCount' : IDL.Nat,
          'recentTransfers' : IDL.Vec(MoneyTransfer),
          'cardCount' : IDL.Nat,
          'emiPlansCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getEmiPlans' : IDL.Func([], [IDL.Vec(EmiPlan)], ['query']),
  'getInsuranceInquiries' : IDL.Func(
      [],
      [IDL.Vec(InsuranceInquiry)],
      ['query'],
    ),
  'getLoanApplications' : IDL.Func([], [IDL.Vec(LoanApplication)], ['query']),
  'getTransferHistory' : IDL.Func([], [IDL.Vec(MoneyTransfer)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeCard' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveEmiPlan' : IDL.Func(
      [Amount, IDL.Float64, IDL.Nat, IDL.Float64, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'submitInsuranceInquiry' : IDL.Func(
      [InsuranceCategory, Amount, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CardType = IDL.Variant({ 'credit' : IDL.Null, 'debit' : IDL.Null });
  const LoanType = IDL.Variant({
    'home' : IDL.Null,
    'business' : IDL.Null,
    'vehicle' : IDL.Null,
  });
  const Amount = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AccountLabel = IDL.Text;
  const TransferType = IDL.Variant({
    'imps' : IDL.Null,
    'neft' : IDL.Null,
    'rtgs' : IDL.Null,
  });
  const Card = IDL.Record({
    'nickname' : IDL.Text,
    'cardType' : CardType,
    'last4' : IDL.Text,
    'issuer' : IDL.Text,
    'expiry' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const TransferStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Time = IDL.Int;
  const MoneyTransfer = IDL.Record({
    'status' : TransferStatus,
    'transferType' : TransferType,
    'fromAccount' : AccountLabel,
    'beneficiary' : IDL.Text,
    'note' : IDL.Text,
    'timestamp' : Time,
    'amount' : Amount,
  });
  const EmiPlan = IDL.Record({
    'emi' : IDL.Float64,
    'principal' : Amount,
    'createdAt' : Time,
    'rate' : IDL.Float64,
    'totalInterest' : IDL.Float64,
    'tenureMonths' : IDL.Nat,
    'totalPayment' : IDL.Float64,
  });
  const InsuranceCategory = IDL.Variant({
    'home' : IDL.Null,
    'life' : IDL.Null,
    'vehicle' : IDL.Null,
    'health' : IDL.Null,
  });
  const InsuranceInquiry = IDL.Record({
    'status' : IDL.Variant({ 'submitted' : IDL.Null, 'reviewed' : IDL.Null }),
    'notes' : IDL.Text,
    'timestamp' : Time,
    'category' : InsuranceCategory,
    'coverageAmount' : Amount,
    'contactPreference' : IDL.Text,
  });
  const LoanApplication = IDL.Record({
    'status' : IDL.Variant({
      'submitted' : IDL.Null,
      'underReview' : IDL.Null,
    }),
    'documents' : IDL.Text,
    'name' : IDL.Text,
    'loanType' : LoanType,
    'income' : Amount,
    'timestamp' : Time,
    'tenure' : IDL.Nat,
    'amount' : Amount,
    'purpose' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCard' : IDL.Func(
        [IDL.Text, CardType, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'applyLoan' : IDL.Func(
        [LoanType, IDL.Text, Amount, IDL.Nat, Amount, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTransfer' : IDL.Func(
        [AccountLabel, IDL.Text, Amount, IDL.Text, TransferType],
        [],
        [],
      ),
    'getAllCards' : IDL.Func([], [IDL.Vec(Card)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'loanCount' : IDL.Nat,
            'recentTransfers' : IDL.Vec(MoneyTransfer),
            'cardCount' : IDL.Nat,
            'emiPlansCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getEmiPlans' : IDL.Func([], [IDL.Vec(EmiPlan)], ['query']),
    'getInsuranceInquiries' : IDL.Func(
        [],
        [IDL.Vec(InsuranceInquiry)],
        ['query'],
      ),
    'getLoanApplications' : IDL.Func([], [IDL.Vec(LoanApplication)], ['query']),
    'getTransferHistory' : IDL.Func([], [IDL.Vec(MoneyTransfer)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeCard' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveEmiPlan' : IDL.Func(
        [Amount, IDL.Float64, IDL.Nat, IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'submitInsuranceInquiry' : IDL.Func(
        [InsuranceCategory, Amount, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };