/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountLabel = string;
export type Amount = bigint;
export interface Card {
  'nickname' : string,
  'cardType' : CardType,
  'last4' : string,
  'issuer' : string,
  'expiry' : string,
}
export type CardType = { 'credit' : null } |
  { 'debit' : null };
export interface EmiPlan {
  'emi' : number,
  'principal' : Amount,
  'createdAt' : Time,
  'rate' : number,
  'totalInterest' : number,
  'tenureMonths' : bigint,
  'totalPayment' : number,
}
export type InsuranceCategory = { 'home' : null } |
  { 'life' : null } |
  { 'vehicle' : null } |
  { 'health' : null };
export interface InsuranceInquiry {
  'status' : { 'submitted' : null } |
    { 'reviewed' : null },
  'notes' : string,
  'timestamp' : Time,
  'category' : InsuranceCategory,
  'coverageAmount' : Amount,
  'contactPreference' : string,
}
export interface LoanApplication {
  'status' : { 'submitted' : null } |
    { 'underReview' : null },
  'documents' : string,
  'name' : string,
  'loanType' : LoanType,
  'income' : Amount,
  'timestamp' : Time,
  'tenure' : bigint,
  'amount' : Amount,
  'purpose' : string,
}
export type LoanType = { 'home' : null } |
  { 'business' : null } |
  { 'vehicle' : null };
export interface MoneyTransfer {
  'status' : TransferStatus,
  'transferType' : TransferType,
  'fromAccount' : AccountLabel,
  'beneficiary' : string,
  'note' : string,
  'timestamp' : Time,
  'amount' : Amount,
}
export type Time = bigint;
export type TransferStatus = { 'submitted' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type TransferType = { 'imps' : null } |
  { 'neft' : null } |
  { 'rtgs' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCard' : ActorMethod<
    [string, CardType, string, string, string],
    undefined
  >,
  'applyLoan' : ActorMethod<
    [LoanType, string, Amount, bigint, Amount, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTransfer' : ActorMethod<
    [AccountLabel, string, Amount, string, TransferType],
    undefined
  >,
  'getAllCards' : ActorMethod<[], Array<Card>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardSummary' : ActorMethod<
    [],
    {
      'loanCount' : bigint,
      'recentTransfers' : Array<MoneyTransfer>,
      'cardCount' : bigint,
      'emiPlansCount' : bigint,
    }
  >,
  'getEmiPlans' : ActorMethod<[], Array<EmiPlan>>,
  'getInsuranceInquiries' : ActorMethod<[], Array<InsuranceInquiry>>,
  'getLoanApplications' : ActorMethod<[], Array<LoanApplication>>,
  'getTransferHistory' : ActorMethod<[], Array<MoneyTransfer>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeCard' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveEmiPlan' : ActorMethod<
    [Amount, number, bigint, number, number, number],
    undefined
  >,
  'submitInsuranceInquiry' : ActorMethod<
    [InsuranceCategory, Amount, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];