/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Card {
    nickname: string;
    cardType: CardType;
    last4: string;
    issuer: string;
    expiry: string;
}
export type Time = bigint;
export interface EmiPlan {
    emi: number;
    principal: Amount;
    createdAt: Time;
    rate: number;
    totalInterest: number;
    tenureMonths: bigint;
    totalPayment: number;
}
export type Amount = bigint;
export type AccountLabel = string;
export interface InsuranceInquiry {
    status: Variant_submitted_reviewed;
    notes: string;
    timestamp: Time;
    category: InsuranceCategory;
    coverageAmount: Amount;
    contactPreference: string;
}
export interface MoneyTransfer {
    status: TransferStatus;
    transferType: TransferType;
    fromAccount: AccountLabel;
    beneficiary: string;
    note: string;
    timestamp: Time;
    amount: Amount;
}
export interface LoanApplication {
    status: Variant_submitted_underReview;
    documents: string;
    name: string;
    loanType: LoanType;
    income: Amount;
    timestamp: Time;
    tenure: bigint;
    amount: Amount;
    purpose: string;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export enum CardType {
    credit = "credit",
    debit = "debit"
}
export enum InsuranceCategory {
    home = "home",
    life = "life",
    vehicle = "vehicle",
    health = "health"
}
export enum LoanType {
    home = "home",
    business = "business",
    vehicle = "vehicle"
}
export enum TransferStatus {
    submitted = "submitted",
    completed = "completed",
    failed = "failed"
}
export enum TransferType {
    imps = "imps",
    neft = "neft",
    rtgs = "rtgs"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_submitted_reviewed {
    submitted = "submitted",
    reviewed = "reviewed"
}
export enum Variant_submitted_underReview {
    submitted = "submitted",
    underReview = "underReview"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCard(nickname: string, cardType: CardType, issuer: string, last4: string, expiry: string): Promise<void>;
    applyLoan(loanType: LoanType, name: string, amount: Amount, tenure: bigint, income: Amount, purpose: string, documents: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createTransfer(fromAccount: AccountLabel, beneficiary: string, amount: Amount, note: string, transferType: TransferType): Promise<void>;
    getAllCards(): Promise<Array<Card>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardSummary(): Promise<{
        loanCount: bigint;
        recentTransfers: Array<MoneyTransfer>;
        cardCount: bigint;
        emiPlansCount: bigint;
    }>;
    getEmiPlans(): Promise<Array<EmiPlan>>;
    getInsuranceInquiries(): Promise<Array<InsuranceInquiry>>;
    getLoanApplications(): Promise<Array<LoanApplication>>;
    getTransferHistory(): Promise<Array<MoneyTransfer>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeCard(nickname: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveEmiPlan(principal: Amount, rate: number, tenureMonths: bigint, emi: number, totalPayment: number, totalInterest: number): Promise<void>;
    submitInsuranceInquiry(category: InsuranceCategory, coverageAmount: Amount, notes: string, contactPreference: string): Promise<void>;
}
import type { AccountLabel as _AccountLabel, Amount as _Amount, Card as _Card, CardType as _CardType, InsuranceCategory as _InsuranceCategory, InsuranceInquiry as _InsuranceInquiry, LoanApplication as _LoanApplication, LoanType as _LoanType, MoneyTransfer as _MoneyTransfer, Time as _Time, TransferStatus as _TransferStatus, TransferType as _TransferType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCard(arg0: string, arg1: CardType, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCard(arg0, to_candid_CardType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCard(arg0, to_candid_CardType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async applyLoan(arg0: LoanType, arg1: string, arg2: Amount, arg3: bigint, arg4: Amount, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyLoan(to_candid_LoanType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyLoan(to_candid_LoanType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTransfer(arg0: AccountLabel, arg1: string, arg2: Amount, arg3: string, arg4: TransferType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTransfer(arg0, arg1, arg2, arg3, to_candid_TransferType_n7(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTransfer(arg0, arg1, arg2, arg3, to_candid_TransferType_n7(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async getAllCards(): Promise<Array<Card>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCards();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCards();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardSummary(): Promise<{
        loanCount: bigint;
        recentTransfers: Array<MoneyTransfer>;
        cardCount: bigint;
        emiPlansCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary();
                return from_candid_record_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary();
            return from_candid_record_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmiPlans(): Promise<Array<EmiPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmiPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmiPlans();
            return result;
        }
    }
    async getInsuranceInquiries(): Promise<Array<InsuranceInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInsuranceInquiries();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInsuranceInquiries();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoanApplications(): Promise<Array<LoanApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoanApplications();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoanApplications();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransferHistory(): Promise<Array<MoneyTransfer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransferHistory();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransferHistory();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeCard(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCard(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveEmiPlan(arg0: Amount, arg1: number, arg2: bigint, arg3: number, arg4: number, arg5: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEmiPlan(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEmiPlan(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async submitInsuranceInquiry(arg0: InsuranceCategory, arg1: Amount, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInsuranceInquiry(to_candid_InsuranceCategory_n37(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInsuranceInquiry(to_candid_InsuranceCategory_n37(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_CardType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CardType): CardType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Card_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Card): Card {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_InsuranceCategory_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InsuranceCategory): InsuranceCategory {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_InsuranceInquiry_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InsuranceInquiry): InsuranceInquiry {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_LoanApplication_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanApplication): LoanApplication {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_LoanType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanType): LoanType {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_MoneyTransfer_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MoneyTransfer): MoneyTransfer {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_TransferStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransferStatus): TransferStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_TransferType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransferType): TransferType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nickname: string;
    cardType: _CardType;
    last4: string;
    issuer: string;
    expiry: string;
}): {
    nickname: string;
    cardType: CardType;
    last4: string;
    issuer: string;
    expiry: string;
} {
    return {
        nickname: value.nickname,
        cardType: from_candid_CardType_n12(_uploadFile, _downloadFile, value.cardType),
        last4: value.last4,
        issuer: value.issuer,
        expiry: value.expiry
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    loanCount: bigint;
    recentTransfers: Array<_MoneyTransfer>;
    cardCount: bigint;
    emiPlansCount: bigint;
}): {
    loanCount: bigint;
    recentTransfers: Array<MoneyTransfer>;
    cardCount: bigint;
    emiPlansCount: bigint;
} {
    return {
        loanCount: value.loanCount,
        recentTransfers: from_candid_vec_n18(_uploadFile, _downloadFile, value.recentTransfers),
        cardCount: value.cardCount,
        emiPlansCount: value.emiPlansCount
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TransferStatus;
    transferType: _TransferType;
    fromAccount: _AccountLabel;
    beneficiary: string;
    note: string;
    timestamp: _Time;
    amount: _Amount;
}): {
    status: TransferStatus;
    transferType: TransferType;
    fromAccount: AccountLabel;
    beneficiary: string;
    note: string;
    timestamp: Time;
    amount: Amount;
} {
    return {
        status: from_candid_TransferStatus_n21(_uploadFile, _downloadFile, value.status),
        transferType: from_candid_TransferType_n23(_uploadFile, _downloadFile, value.transferType),
        fromAccount: value.fromAccount,
        beneficiary: value.beneficiary,
        note: value.note,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        submitted: null;
    } | {
        reviewed: null;
    };
    notes: string;
    timestamp: _Time;
    category: _InsuranceCategory;
    coverageAmount: _Amount;
    contactPreference: string;
}): {
    status: Variant_submitted_reviewed;
    notes: string;
    timestamp: Time;
    category: InsuranceCategory;
    coverageAmount: Amount;
    contactPreference: string;
} {
    return {
        status: from_candid_variant_n28(_uploadFile, _downloadFile, value.status),
        notes: value.notes,
        timestamp: value.timestamp,
        category: from_candid_InsuranceCategory_n29(_uploadFile, _downloadFile, value.category),
        coverageAmount: value.coverageAmount,
        contactPreference: value.contactPreference
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        submitted: null;
    } | {
        underReview: null;
    };
    documents: string;
    name: string;
    loanType: _LoanType;
    income: _Amount;
    timestamp: _Time;
    tenure: bigint;
    amount: _Amount;
    purpose: string;
}): {
    status: Variant_submitted_underReview;
    documents: string;
    name: string;
    loanType: LoanType;
    income: Amount;
    timestamp: Time;
    tenure: bigint;
    amount: Amount;
    purpose: string;
} {
    return {
        status: from_candid_variant_n34(_uploadFile, _downloadFile, value.status),
        documents: value.documents,
        name: value.name,
        loanType: from_candid_LoanType_n35(_uploadFile, _downloadFile, value.loanType),
        income: value.income,
        timestamp: value.timestamp,
        tenure: value.tenure,
        amount: value.amount,
        purpose: value.purpose
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    credit: null;
} | {
    debit: null;
}): CardType {
    return "credit" in value ? CardType.credit : "debit" in value ? CardType.debit : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    completed: null;
} | {
    failed: null;
}): TransferStatus {
    return "submitted" in value ? TransferStatus.submitted : "completed" in value ? TransferStatus.completed : "failed" in value ? TransferStatus.failed : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    imps: null;
} | {
    neft: null;
} | {
    rtgs: null;
}): TransferType {
    return "imps" in value ? TransferType.imps : "neft" in value ? TransferType.neft : "rtgs" in value ? TransferType.rtgs : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    reviewed: null;
}): Variant_submitted_reviewed {
    return "submitted" in value ? Variant_submitted_reviewed.submitted : "reviewed" in value ? Variant_submitted_reviewed.reviewed : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    home: null;
} | {
    life: null;
} | {
    vehicle: null;
} | {
    health: null;
}): InsuranceCategory {
    return "home" in value ? InsuranceCategory.home : "life" in value ? InsuranceCategory.life : "vehicle" in value ? InsuranceCategory.vehicle : "health" in value ? InsuranceCategory.health : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    underReview: null;
}): Variant_submitted_underReview {
    return "submitted" in value ? Variant_submitted_underReview.submitted : "underReview" in value ? Variant_submitted_underReview.underReview : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    home: null;
} | {
    business: null;
} | {
    vehicle: null;
}): LoanType {
    return "home" in value ? LoanType.home : "business" in value ? LoanType.business : "vehicle" in value ? LoanType.vehicle : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MoneyTransfer>): Array<MoneyTransfer> {
    return value.map((x)=>from_candid_MoneyTransfer_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InsuranceInquiry>): Array<InsuranceInquiry> {
    return value.map((x)=>from_candid_InsuranceInquiry_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LoanApplication>): Array<LoanApplication> {
    return value.map((x)=>from_candid_LoanApplication_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Card>): Array<Card> {
    return value.map((x)=>from_candid_Card_n10(_uploadFile, _downloadFile, x));
}
function to_candid_CardType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CardType): _CardType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_InsuranceCategory_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InsuranceCategory): _InsuranceCategory {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_LoanType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoanType): _LoanType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TransferType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransferType): _TransferType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CardType): {
    credit: null;
} | {
    debit: null;
} {
    return value == CardType.credit ? {
        credit: null
    } : value == CardType.debit ? {
        debit: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InsuranceCategory): {
    home: null;
} | {
    life: null;
} | {
    vehicle: null;
} | {
    health: null;
} {
    return value == InsuranceCategory.home ? {
        home: null
    } : value == InsuranceCategory.life ? {
        life: null
    } : value == InsuranceCategory.vehicle ? {
        vehicle: null
    } : value == InsuranceCategory.health ? {
        health: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoanType): {
    home: null;
} | {
    business: null;
} | {
    vehicle: null;
} {
    return value == LoanType.home ? {
        home: null
    } : value == LoanType.business ? {
        business: null
    } : value == LoanType.vehicle ? {
        vehicle: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransferType): {
    imps: null;
} | {
    neft: null;
} | {
    rtgs: null;
} {
    return value == TransferType.imps ? {
        imps: null
    } : value == TransferType.neft ? {
        neft: null
    } : value == TransferType.rtgs ? {
        rtgs: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
